// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SequencialUnico.proto
// Protobuf Java Version: 4.32.1
package org.br.mineradora.singleton.grpc.identificador;

/**
 * Protobuf type {@code Identificador}
 */
@com.google.protobuf.Generated
public final class Identificador extends com.google.protobuf.GeneratedMessage implements // @@protoc_insertion_point(message_implements:Identificador)
IdentificadorOrBuilder {

    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
        4, /* minor= */
        32, /* patch= */
        1, /* suffix= */
        "", Identificador.class.getName());
    }

    // Use Identificador.newBuilder() to construct.
    private Identificador(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private Identificador() {
        uuid_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return org.br.mineradora.singleton.grpc.identificador.SingletonGrpc.internal_static_Identificador_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return org.br.mineradora.singleton.grpc.identificador.SingletonGrpc.internal_static_Identificador_fieldAccessorTable.ensureFieldAccessorsInitialized(org.br.mineradora.singleton.grpc.identificador.Identificador.class, org.br.mineradora.singleton.grpc.identificador.Identificador.Builder.class);
    }

    public static final int SEQUENCIAL_FIELD_NUMBER = 1;

    private long sequencial_ = 0L;

    /**
     * <code>int64 sequencial = 1;</code>
     * @return The sequencial.
     */
    @java.lang.Override
    public long getSequencial() {
        return sequencial_;
    }

    public static final int UUID_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";

    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uuid_ = s;
            return s;
        }
    }

    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            uuid_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int DATA_FIELD_NUMBER = 3;

    private long data_ = 0L;

    /**
     * <code>int64 data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public long getData() {
        return data_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (sequencial_ != 0L) {
            output.writeInt64(1, sequencial_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 2, uuid_);
        }
        if (data_ != 0L) {
            output.writeInt64(3, data_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        size = 0;
        if (sequencial_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, sequencial_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(2, uuid_);
        }
        if (data_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, data_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.br.mineradora.singleton.grpc.identificador.Identificador)) {
            return super.equals(obj);
        }
        org.br.mineradora.singleton.grpc.identificador.Identificador other = (org.br.mineradora.singleton.grpc.identificador.Identificador) obj;
        if (getSequencial() != other.getSequencial())
            return false;
        if (!getUuid().equals(other.getUuid()))
            return false;
        if (getData() != other.getData())
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SEQUENCIAL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getSequencial());
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getData());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.br.mineradora.singleton.grpc.identificador.Identificador prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code Identificador}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements // @@protoc_insertion_point(builder_implements:Identificador)
    org.br.mineradora.singleton.grpc.identificador.IdentificadorOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return org.br.mineradora.singleton.grpc.identificador.SingletonGrpc.internal_static_Identificador_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return org.br.mineradora.singleton.grpc.identificador.SingletonGrpc.internal_static_Identificador_fieldAccessorTable.ensureFieldAccessorsInitialized(org.br.mineradora.singleton.grpc.identificador.Identificador.class, org.br.mineradora.singleton.grpc.identificador.Identificador.Builder.class);
        }

        // Construct using org.br.mineradora.singleton.grpc.identificador.Identificador.newBuilder()
        private Builder() {
        }

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            sequencial_ = 0L;
            uuid_ = "";
            data_ = 0L;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return org.br.mineradora.singleton.grpc.identificador.SingletonGrpc.internal_static_Identificador_descriptor;
        }

        @java.lang.Override
        public org.br.mineradora.singleton.grpc.identificador.Identificador getDefaultInstanceForType() {
            return org.br.mineradora.singleton.grpc.identificador.Identificador.getDefaultInstance();
        }

        @java.lang.Override
        public org.br.mineradora.singleton.grpc.identificador.Identificador build() {
            org.br.mineradora.singleton.grpc.identificador.Identificador result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.br.mineradora.singleton.grpc.identificador.Identificador buildPartial() {
            org.br.mineradora.singleton.grpc.identificador.Identificador result = new org.br.mineradora.singleton.grpc.identificador.Identificador(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(org.br.mineradora.singleton.grpc.identificador.Identificador result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.sequencial_ = sequencial_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.uuid_ = uuid_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.data_ = data_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.br.mineradora.singleton.grpc.identificador.Identificador) {
                return mergeFrom((org.br.mineradora.singleton.grpc.identificador.Identificador) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.br.mineradora.singleton.grpc.identificador.Identificador other) {
            if (other == org.br.mineradora.singleton.grpc.identificador.Identificador.getDefaultInstance())
                return this;
            if (other.getSequencial() != 0L) {
                setSequencial(other.getSequencial());
            }
            if (!other.getUuid().isEmpty()) {
                uuid_ = other.uuid_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (other.getData() != 0L) {
                setData(other.getData());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch(tag) {
                        case 0:
                            done = true;
                            break;
                        case 8:
                            {
                                sequencial_ = input.readInt64();
                                bitField0_ |= 0x00000001;
                                break;
                            }
                        // case 8
                        case 18:
                            {
                                uuid_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            }
                        // case 18
                        case 24:
                            {
                                data_ = input.readInt64();
                                bitField0_ |= 0x00000004;
                                break;
                            }
                        // case 24
                        default:
                            {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    // was an endgroup tag
                                    done = true;
                                }
                                break;
                            }
                    }
                    // switch (tag)
                }
                // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            }
            // finally
            return this;
        }

        private int bitField0_;

        private long sequencial_;

        /**
         * <code>int64 sequencial = 1;</code>
         * @return The sequencial.
         */
        @java.lang.Override
        public long getSequencial() {
            return sequencial_;
        }

        /**
         * <code>int64 sequencial = 1;</code>
         * @param value The sequencial to set.
         * @return This builder for chaining.
         */
        public Builder setSequencial(long value) {
            sequencial_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>int64 sequencial = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearSequencial() {
            bitField0_ = (bitField0_ & ~0x00000001);
            sequencial_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object uuid_ = "";

        /**
         * <code>string uuid = 2;</code>
         * @return The uuid.
         */
        public java.lang.String getUuid() {
            java.lang.Object ref = uuid_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uuid_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string uuid = 2;</code>
         * @return The bytes for uuid.
         */
        public com.google.protobuf.ByteString getUuidBytes() {
            java.lang.Object ref = uuid_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                uuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string uuid = 2;</code>
         * @param value The uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuid(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            uuid_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearUuid() {
            uuid_ = getDefaultInstance().getUuid();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>string uuid = 2;</code>
         * @param value The bytes for uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuidBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            uuid_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private long data_;

        /**
         * <code>int64 data = 3;</code>
         * @return The data.
         */
        @java.lang.Override
        public long getData() {
            return data_;
        }

        /**
         * <code>int64 data = 3;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(long value) {
            data_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>int64 data = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
            bitField0_ = (bitField0_ & ~0x00000004);
            data_ = 0L;
            onChanged();
            return this;
        }
        // @@protoc_insertion_point(builder_scope:Identificador)
    }

    // @@protoc_insertion_point(class_scope:Identificador)
    private static final org.br.mineradora.singleton.grpc.identificador.Identificador DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.br.mineradora.singleton.grpc.identificador.Identificador();
    }

    public static org.br.mineradora.singleton.grpc.identificador.Identificador getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Identificador> PARSER = new com.google.protobuf.AbstractParser<Identificador>() {

        @java.lang.Override
        public Identificador parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<Identificador> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Identificador> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.br.mineradora.singleton.grpc.identificador.Identificador getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
