// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SequencialUnico.proto
// Protobuf Java Version: 4.32.1
package org.br.mineradora.singleton.grpc.identificador;

@com.google.protobuf.Generated
public interface IdentificadorOrBuilder extends // @@protoc_insertion_point(interface_extends:Identificador)
com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 sequencial = 1;</code>
     * @return The sequencial.
     */
    long getSequencial();

    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();

    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString getUuidBytes();

    /**
     * <code>int64 data = 3;</code>
     * @return The data.
     */
    long getData();
}
