// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SequencialUnico.proto
// Protobuf Java Version: 4.32.1
package org.br.mineradora.singleton.grpc.identificador;

@com.google.protobuf.Generated
public final class SingletonGrpc extends com.google.protobuf.GeneratedFile {

    private SingletonGrpc() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */
        4, /* minor= */
        32, /* patch= */
        1, /* suffix= */
        "", SingletonGrpc.class.getName());
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_Identificador_descriptor;

    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Identificador_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = { "\n\025SequencialUnico.proto\032\033google/protobuf" + "/empty.proto\"?\n\rIdentificador\022\022\n\nsequenc" + "ial\030\001 \001(\003\022\014\n\004uuid\030\002 \001(\t\022\014\n\004data\030\003 \001(\0032V\n" + "\024SingletonServiceGrpc\022>\n\022gerarIdentifica" + "dor\022\026.google.protobuf.Empty\032\016.Identifica" + "dor\"\000BA\n.org.br.mineradora.singleton.grp" + "c.identificadorB\rSingletonGrpcP\001b\006proto3" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] { com.google.protobuf.EmptyProto.getDescriptor() });
        internal_static_Identificador_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Identificador_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_Identificador_descriptor, new java.lang.String[] { "Sequencial", "Uuid", "Data" });
        descriptor.resolveAllFeaturesImmutable();
        com.google.protobuf.EmptyProto.getDescriptor();
    }
    // @@protoc_insertion_point(outer_class_scope)
}
