#Configuração do envio de vento ao Kafka
mp.messaging.incoming.proposal-channel.connector=smallrye-kafka
mp.messaging.incoming.proposal-channel.topic=proposal

mp.messaging.incoming.quotation-channel.connector=smallrye-kafka
mp.messaging.incoming.quotation-channel.topic=quotation

mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:19092

# Configuração dp datasource
quarkus.datasource.db-king=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/report_db
quarkus.hibernate-orm.database.generation=update

quarkus.http.port=8092
dev.quarkus.http.port=8882

