# Define o pacote base para as classes (Models e APIs) geradas do teste.json
quarkus.openapi-generator.codegen.spec.proposta_json.base-package=org.br.mineradora.gateway.client.generate

quarkus.openapi-generator.codegen.spec.proposta_json.remove-operation-id-prefix=true
quarkus.openapi-generator.codegen.spec.proposta_json.use-field-name-in-part-filename=false

quarkus.openapi-generator.codegen.spec.proposta_json.additional-api-type-annotations=@org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders;@org.br.mineradora.library.interceptor.CustomExceptionHandling;@org.eclipse.microprofile.rest.client.annotation.RegisterProvider(io.quarkus.oidc.token.propagation.reactive.AccessTokenRequestReactiveFilter.class)

# (Opcional) Habilita o uso de Uni (Mutiny) se você estiver em um ambiente reativo
#quarkus.openapi-generator.codegen.spec.teste_json.mutiny=true

#https://docs.quarkiverse.io/quarkus-openapi-generator/dev/client.html#_example
