# Go to http://localhost:8443 when started

####################################################################################################
# DO NOT USE IT IN PRODUCTION
####################################################################################################

name: br-mineradora
services:
  br-mineradora-cotacao:
    image: quarkus/org.br.mineradora.cotacao-jvm
  br-mineradora-proposal:
    image: quarkus/org.br.mineradora.proposta-jvm
    hostname: br-mineradora-proposal
    ports:
      - "9001:8080"
  br-mineradora-report:
    image: quarkus/org.br.mineradora.report-jvm
    hostname: br-mineradora-report
    ports:
      - "9002:8080"
  br-mineradora-bff:
    image: quarkus/org.br.mineradora.gateway-bff-jvm
    hostname: br-mineradora-gateway
    ports:
      - "9003:8080"
      - "8443:8443"
    volumes:
      # Formato: nome-do-volume:caminho-no-container
      - org_br_mineradora:/opt/variaveis:ro
    #Copia o arquivo com as variaveis de ambiente para a pasta deployments
    entrypoint: ["sh", "-c", "cp /opt/variaveis/gateway/.env /deployments/ && /opt/jboss/container/java/run/run-java.sh"]
    depends_on:
      - br-mineradora-report
      - br-mineradora-proposal

volumes:
  org_br_mineradora:
    external: true