quarkus.http.port=8095
dev.quarkus.http.port=8885

# Configuração da segurança com keycloak
quarkus.oidc.auth-server-url=http://localhost:8081/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}

#Rest client Configuration com quarkus-rest-client-oidc-token-propagation
org.br.mineradoria.gateway.client.ProposalClient/mp-rest/url=http://localhost:8091
org.br.mineradoria.gateway.client.ReportClient/mp-rest/url=http://localhost:8092

#https://pt.quarkus.io/guides/openapi-swaggerui
quarkus.swagger-ui.always-include = true
quarkus.smallrye-openapi.info-description = BR mineradora : Trade de Minerio

#https://quarkus.io/guides/opentelemetry
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
quarkus.application.name=gateway-bff 
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
#quarkus.otel.exporter.otlp.headers=authorization=Bearer my_secret 
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n  