quarkus.http.port=8095
dev.quarkus.http.port=8885

# Configuração da segurança com keycloak
quarkus.oidc.auth-server-url=http://localhost:8081/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}

#Rest client Configuration com quarkus-rest-client-oidc-token-propagation
org.br.mineradoria.gateway.client.ProposalClient/mp-rest/url=http://localhost:8091
org.br.mineradoria.gateway.client.ReportClient/mp-rest/url=http://localhost:8092

quarkus.swagger-ui.always-include = true
quarkus.dmsllrye-openapi.info-description = BR mineradora : Trade de Minerio
