quarkus.http.port=8091
#dev.quarkus.http.port=8001

#Rest client Configuration com quarkus-rest-client-oidc-token-propagation
org.br.mineradora.gateway.client.proposta.ProposalClient/mp-rest/url=http://192.168.56.1:9001
org.br.mineradora.gateway.client.ReportClient/mp-rest/url=http://192.168.56.1:8080

# Rest client configuração
quarkus.rest-client."org.br.mineradora.gateway.client.OAuthClient".url=http://192.168.56.1:8081

#Configuração do envio de vento ao Kafka
mp.messaging.outgoing.proposal-channel.connector=smallrye-kafka
mp.messaging.outgoing.proposal-channel.topic=proposal
mp.messaging.connector.smallrye-kafka.bootstrap.servers=192.168.56.1:19092

# Configuração dp datasource
quarkus.datasource.db-king=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.56.1:5432/proposal_db
quarkus.hibernate-orm.database.generation=update



# Configuração da segurança com keycloak
quarkus.oidc.auth-server-url=http://192.168.56.1:8081/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

quarkus.log.category."org.br.mineradora.gateway.rs.filter.LoggingFilter".level=INFO

#https://quarkus.io/guides/opentelemetry
#quarkus.otel.metrics.enabled=true
#quarkus.otel.logs.enabled=true
#quarkus.application.name=proposta
#quarkus.otel.exporter.otlp.endpoint=http://192.168.56.1:4317
#quarkus.otel.exporter.otlp.headers=authorization=Bearer my_secret 
#quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n  


quarkus.grpc.clients.identificador.host=192.168.56.1
quarkus.grpc.clients.identificador.port=9090