<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.br.mineradora</groupId>
	<artifactId>org.br.mineradora.gateway-bff.parent</artifactId>
	<version>1.0.0.1</version>
	<packaging>pom</packaging>

	<properties>
		<compiler-plugin.version>3.14.1</compiler-plugin.version>
		<maven.compiler.release>21</maven.compiler.release>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
		<quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
		<quarkus.platform.version>3.31.3</quarkus.platform.version>
		<skipITs>true</skipITs>
		<surefire-plugin.version>3.5.4</surefire-plugin.version>
		<global.project.version>1.0.0.1</global.project.version>
	</properties>


	<!-- https://github.com/lssoares/multi-maven-quarkus/blob/master/pom.xml-->

	<!--https://github.com/Rashmini/Quarkus-multimodule-project-->

	<!--
	https://stackoverflow.com/questions/78088326/quarkus-multi-module-maven-project-with-integration-tests-problems-with-includi-->
	<modules>
		<module>../org.br.mineradora.gateway-bff.client</module>
		<module>../org.br.mineradora.gateway-bff.bo</module>
		<module>../org.br.mineradora.gateway-bff.rs</module>
		<module>../org.br.mineradora.gateway-bff.run</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>${quarkus.platform.artifact-id}</artifactId>
				<version>${quarkus.platform.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>io.quarkiverse.openapi.generator</groupId>
				<artifactId>quarkus-openapi-generator</artifactId>
				<version>2.14.0-lts</version>
			</dependency>
		</dependencies>
	</dependencyManagement>


	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<version>2.7</version>
					<goals>
						<goal>set</goal>
					</goals>
					<configuration>
						<newVersion>${global.project.version}</newVersion>
						<allowDowngrade>true</allowDowngrade>
						<generateBackupPoms>false</generateBackupPoms>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${compiler-plugin.version}</version>
					<configuration>
						<parameters>true</parameters>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${surefire-plugin.version}</version>
					<configuration>
						<argLine>@{argLine}</argLine>
						<systemPropertyVariables>
							<java.util.logging.manager>
								org.jboss.logmanager.LogManager</java.util.logging.manager>
							<maven.home>${maven.home}</maven.home>
						</systemPropertyVariables>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>${surefire-plugin.version}</version>
					<executions>
						<execution>
							<goals>
								<goal>integration-test</goal>
								<goal>verify</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<argLine>@{argLine}</argLine>
						<systemPropertyVariables>
							<native.image.path>
								${project.build.directory}/${project.build.finalName}-runner</native.image.path>
							<java.util.logging.manager>
								org.jboss.logmanager.LogManager</java.util.logging.manager>
							<maven.home>${maven.home}</maven.home>
						</systemPropertyVariables>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
