/*
 * report  API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.br.mineradora.gateway.client.report.to;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import jakarta.json.bind.annotation.JsonbProperty;


public class OpportunityDTO  implements Serializable {

  private static final long serialVersionUID = 1L;
  
  @JsonbProperty("proposalId")
  private Long proposalId;

  @JsonbProperty("customer")
  private String customer;

  @JsonbProperty("priceTonne")
  private BigDecimal priceTonne;

  @JsonbProperty("lastDollarQuotation")
  private BigDecimal lastDollarQuotation;


  /**
   * Get proposalId
   * @return proposalId
   **/
  public Long getProposalId() {
    return proposalId;
  }

  /**
   * Set proposalId
   */
  public void setProposalId(Long proposalId) {
    this.proposalId = proposalId;
  }

  public OpportunityDTO proposalId(Long proposalId) {
    this.proposalId = proposalId;
    return this;
  }

  /**
   * Get customer
   * @return customer
   **/
  public String getCustomer() {
    return customer;
  }

  /**
   * Set customer
   */
  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public OpportunityDTO customer(String customer) {
    this.customer = customer;
    return this;
  }

  /**
   * Get priceTonne
   * @return priceTonne
   **/
  public BigDecimal getPriceTonne() {
    return priceTonne;
  }

  /**
   * Set priceTonne
   */
  public void setPriceTonne(BigDecimal priceTonne) {
    this.priceTonne = priceTonne;
  }

  public OpportunityDTO priceTonne(BigDecimal priceTonne) {
    this.priceTonne = priceTonne;
    return this;
  }

  /**
   * Get lastDollarQuotation
   * @return lastDollarQuotation
   **/
  public BigDecimal getLastDollarQuotation() {
    return lastDollarQuotation;
  }

  /**
   * Set lastDollarQuotation
   */
  public void setLastDollarQuotation(BigDecimal lastDollarQuotation) {
    this.lastDollarQuotation = lastDollarQuotation;
  }

  public OpportunityDTO lastDollarQuotation(BigDecimal lastDollarQuotation) {
    this.lastDollarQuotation = lastDollarQuotation;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpportunityDTO opportunityDTO = (OpportunityDTO) o;
    return Objects.equals(this.proposalId, opportunityDTO.proposalId) &&
        Objects.equals(this.customer, opportunityDTO.customer) &&
        Objects.equals(this.priceTonne, opportunityDTO.priceTonne) &&
        Objects.equals(this.lastDollarQuotation, opportunityDTO.lastDollarQuotation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proposalId, customer, priceTonne, lastDollarQuotation);
  }

  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpportunityDTO {\n");
    
    sb.append("    proposalId: ").append(toIndentedString(proposalId)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    priceTonne: ").append(toIndentedString(priceTonne)).append("\n");
    sb.append("    lastDollarQuotation: ").append(toIndentedString(lastDollarQuotation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
