#Configuração do envio de vento ao Kafka
mp.messaging.outgoing.quotation-channel.connector=smallrye-kafka
mp.messaging.outgoing.quotation-channel.topic=quotation
#mp.messaging.connector.smallrye-kafka.bootstrap.servers=192.168.56.1:19092

%prod.kafka.bootstrap.servers=192.168.56.1:19092 

# Configuração dp datasource
quarkus.datasource.db-king=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.56.1:5432/quotation_db
quarkus.hibernate-orm.database.generation=update

#quarkus.http.port=8091
#dev.quarkus.http.port=8000
# Rest client configuração
quarkus.rest-client."org.br.mineradora.cotacao.client.CurrencyPriceClient".url=https://economia.awesomeapi.com.br


